"""Add Game model

Revision ID: 680c12ae144c
Revises:
Create Date: 2020-02-07 20:21:51.847989

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "680c12ae144c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_uid", sa.String(length=32), nullable=True),
        sa.Column("word", sa.String(), nullable=True),
        sa.Column("known_letters", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_uid"),
    )
    op.create_index(op.f("ix_game_id"), "game", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_id"), table_name="game")
    op.drop_table("game")
    # ### end Alembic commands ###
